In [1]:
import os
import sklearn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [4]:

cwd = os.getcwd()  # Get the current working directory

def load_data():
    data_filename = "dataset_cybersecurity_michelle.csv"  
    data_path = os.path.join(cwd, '..', 'data','raw', data_filename)  # Construct the full path
    return pd.read_csv(data_path)

# load the dataset
df= load_data()
df.head()

,qty_dot_url,qty_hyphen_url,qty_underline_url,qty_slash_url,qty_questionmark_url,qty_equal_url,qty_at_url,qty_and_url,qty_exclamation_url,qty_space_url,...,qty_ip_resolved,qty_nameservers,qty_mx_servers,ttl_hostname,tls_ssl_certificate,qty_redirects,url_google_index,domain_google_index,url_shortened,phishing
0,1,0,0,1,0,0,0,0,0,0,...,2,2,5,292,0,-1,0,0,0,1
1,2,5,4,2,0,0,0,0,0,0,...,2,4,2,52,0,1,0,0,0,1
2,2,0,0,0,0,0,0,0,0,0,...,2,2,0,298,1,1,0,0,0,0
3,1,1,0,2,0,0,0,0,0,0,...,1,2,5,1792,0,0,0,0,0,1
4,2,1,0,0,0,0,0,0,0,0,...,1,2,1,299,1,1,0,0,0,0

In [7]:
df.info()
df.isnull().sum()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 129698 entries, 0 to 129697
Columns: 112 entries, qty_dot_url to phishing
dtypes: float64(1), int64(111)
memory usage: 110.8 MB

,qty_dot_url,qty_hyphen_url,qty_underline_url,qty_slash_url,qty_questionmark_url,qty_equal_url,qty_at_url,qty_and_url,qty_exclamation_url,qty_space_url,...,qty_ip_resolved,qty_nameservers,qty_mx_servers,ttl_hostname,tls_ssl_certificate,qty_redirects,url_google_index,domain_google_index,url_shortened,phishing
count,129698.000000,129698.000000,129698.000000,129698.000000,129698.000000,129698.000000,129698.000000,129698.000000,129698.000000,129698.000000,...,129698.000000,129698.000000,129698.000000,129698.000000,129698.000000,129698.000000,129698.000000,129698.000000,129698.000000,129698.000000
mean,2.220612,0.370044,0.132392,1.489892,0.010956,0.240459,0.025683,0.163750,0.003547,0.001234,...,1.130788,2.790490,1.710851,5806.972528,0.505382,0.332341,0.001365,0.002051,0.006369,0.402103
std,1.314717,1.199731,0.706240,1.963822,0.123975,1.027070,0.292883,0.991589,0.098266,0.081421,...,0.903889,1.339672,1.714852,10286.320400,0.499973,0.793889,0.052740,0.058474,0.079550,0.490324
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,-1.000000,0.000000,0.000000,-1.000000,0.000000,-1.000000,-1.000000,-1.000000,0.000000,0.000000
25%,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.000000,2.000000,1.000000,291.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.000000,2.000000,1.000000,1796.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,2.000000,0.000000,0.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.000000,4.000000,2.000000,10791.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000
max,24.000000,35.000000,21.000000,44.000000,9.000000,23.000000,43.000000,26.000000,10.000000,9.000000,...,24.000000,20.000000,20.000000,604800.000000,1.000000,17.000000,1.000000,1.000000,1.000000,1.000000

In [11]:
missing_value_df = df[df.isin([-1]).any(axis=1)]
missing_value_df.describe()

,qty_dot_url,qty_hyphen_url,qty_underline_url,qty_slash_url,qty_questionmark_url,qty_equal_url,qty_at_url,qty_and_url,qty_exclamation_url,qty_space_url,...,qty_ip_resolved,qty_nameservers,qty_mx_servers,ttl_hostname,tls_ssl_certificate,qty_redirects,url_google_index,domain_google_index,url_shortened,phishing
count,123600.000000,123600.000000,123600.000000,123600.000000,123600.000000,123600.000000,123600.000000,123600.00000,123600.000000,123600.000000,...,123600.000000,123600.000000,123600.000000,123600.000000,123600.000000,123600.000000,123600.000000,123600.000000,123600.000000,123600.000000
mean,2.162063,0.353924,0.103172,1.398155,0.007201,0.131464,0.016424,0.08589,0.002896,0.001262,...,1.130364,2.801003,1.701820,5815.890316,0.504757,0.337451,0.001432,0.002039,0.006505,0.379207
std,1.148800,1.168554,0.605522,1.911064,0.099008,0.763654,0.276577,0.73638,0.088633,0.083211,...,0.914108,1.354327,1.701828,10448.444483,0.499979,0.804573,0.054025,0.058948,0.080390,0.485192
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,...,-1.000000,0.000000,0.000000,-1.000000,0.000000,-1.000000,-1.000000,-1.000000,0.000000,0.000000
25%,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,...,1.000000,2.000000,1.000000,291.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,...,1.000000,2.000000,1.000000,1792.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,2.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,...,1.000000,4.000000,2.000000,10791.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000
max,23.000000,35.000000,21.000000,44.000000,9.000000,20.000000,43.000000,26.00000,9.000000,9.000000,...,19.000000,20.000000,20.000000,604800.000000,1.000000,17.000000,1.000000,1.000000,1.000000,1.000000

In [12]:
# Create a new DataFrame 'cleaned_df' with -1 replaced by mode
cleaned_df = df.copy()  # Make a copy of the original DataFrame

# Replace -1 with the mean of each column
for col in cleaned_df.columns:
    if -1 in cleaned_df[col].values:
        mean_val = cleaned_df[col][cleaned_df[col] != -1].mean()  # Calculate the mean excluding -1
        cleaned_df[col] = cleaned_df[col].replace(-1, mean_val)
cleaned_df.describe()

,qty_dot_url,qty_hyphen_url,qty_underline_url,qty_slash_url,qty_questionmark_url,qty_equal_url,qty_at_url,qty_and_url,qty_exclamation_url,qty_space_url,...,qty_ip_resolved,qty_nameservers,qty_mx_servers,ttl_hostname,tls_ssl_certificate,qty_redirects,url_google_index,domain_google_index,url_shortened,phishing
count,129698.000000,129698.000000,129698.000000,129698.000000,129698.000000,129698.000000,129698.000000,129698.000000,129698.000000,129698.000000,...,129698.000000,129698.000000,129698.000000,129698.000000,129698.000000,129698.000000,129698.000000,129698.000000,129698.000000,129698.000000
mean,2.220612,0.370044,0.132392,1.489892,0.010956,0.240459,0.025683,0.163750,0.003547,0.001234,...,1.250865,2.790490,1.710851,6134.620671,0.505382,0.452618,0.002076,0.002739,0.006369,0.402103
std,1.314717,1.199731,0.706240,1.963822,0.123975,1.027070,0.292883,0.991589,0.098266,0.081421,...,0.749103,1.339672,1.714852,10193.399888,0.499973,0.685572,0.045495,0.052246,0.079550,0.490324
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.000000,2.000000,1.000000,298.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.000000,2.000000,1.000000,3581.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,2.000000,0.000000,0.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.000000,4.000000,2.000000,10791.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000
max,24.000000,35.000000,21.000000,44.000000,9.000000,23.000000,43.000000,26.000000,10.000000,9.000000,...,24.000000,20.000000,20.000000,604800.000000,1.000000,17.000000,1.000000,1.000000,1.000000,1.000000